name: Cross-Compile Rust App for Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Cache Rust dependencies to speed up builds
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      # Install Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # Configure repositories and install dependencies
      - name: Configure repositories and install dependencies
        run: |
          # Replace Azure mirror with official Ubuntu repositories
          sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/g' /etc/apt/sources.list
          # Ensure ARM64 architecture is enabled
          sudo dpkg --add-architecture arm64
          # Update package lists
          sudo apt-get update
          # Install dependencies
          sudo apt-get install -y libxcb1-dev
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libxcb1-dev:arm64 pkg-config
          fi
          # Debug: Verify ARM64 libraries
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            ls -l /usr/lib/aarch64-linux-gnu/libxcb*
            pkg-config --libs --cflags xcb
          fi

      # Build the Rust application
      - name: Build
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          PKG_CONFIG_aarch64_unknown_linux_gnu: pkg-config
          PKG_CONFIG_PATH_aarch64_unknown_linux_gnu: /usr/lib/aarch64-linux-gnu/pkgconfig
          PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu: /usr/aarch64-linux-gnu
          PKG_CONFIG_ALLOW_CROSS: 1
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS: "-C link-arg=-L/usr/lib/aarch64-linux-gnu"
        run: |
          cargo build --release --target ${{ matrix.target }} --verbose

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/lazyredis
